apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      name: jaeger
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.30.0@sha256:d967699c6b7159fd1ffba29385059ffa899738853c23ed81db23cd8acd0c6805
          env:
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: BADGER_DIRECTORY_VALUE
              value: /badger/data
            - name: BADGER_DIRECTORY_KEY
              value: /badger/key
            - name: BADGER_SPAN_STORE_TTL
              value: 2h
          ports:
            - name: query
              containerPort: 16686
            - name: compact-thrift
              containerPort: 6831
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /
              port: 16686
              scheme: HTTP
          volumeMounts:
            - mountPath: /badger
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: query
      port: 16686
    - name: compact-thrift
      port: 6831
      protocol: UDP
  selector:
    name: jaeger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi