apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: minio
      port: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
        app: minio
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-06-17T00-10-46Z@sha256:429b3934af4b387a00d1edc519da040d8d0d39879523b8fa2e85e8ec451a9736
          args:
            - server
            - /home/shared
          envFrom:
            - secretRef:
                name: minio-credentials
          ports:
            - name: http
              containerPort: 9000
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /home/shared
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minio123
  MINIO_SECRET_KEY: minio456
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-s3-bucket
spec:
  backoffLimit: 20
  template:
    metadata:
      name: setup-s3-bucket
    spec:
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2021-10-07T04-19-58Z@sha256:b46dd550d8930d4a24eeeb3582b65c445974fd64c397d477ffb3932b685e1080
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc mb minio/php-package-cache --ignore-existing
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: minio-credentials
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-all-files
spec:
  backoffLimit: 1
  template:
    metadata:
      name: delete-all-files
    spec:
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2021-10-07T04-19-58Z@sha256:b46dd550d8930d4a24eeeb3582b65c445974fd64c397d477ffb3932b685e1080
          command:
            - sh
            - -c
            - |
              set -euxo pipefail
              mc config host add minio http://minio:9000 $(cat /secret/minio/MINIO_ACCESS_KEY) $(cat /secret/minio/MINIO_SECRET_KEY)
              mc rm -r --force minio/php-package-cache
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
      volumes:
        - name: minio
          secret:
            secretName: minio-credentials
      restartPolicy: Never
