apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: prometheus
      port: 9000
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.33.4@sha256:fb7e3a27469dd7e15f3b181cf510954db04b855722be94448dc23494005c433c
          args:
            - --config.file=/config/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 5Gi
            requests:
              cpu: 200m
              memory: 5Gi
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
          volumeMounts:
            - mountPath: /prometheus
              name: data
            - mountPath: /config
              name: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - php-package-cache:8080
