
k8s_yaml('minio.yaml')
k8s_resource('minio', port_forwards=['9000'])
k8s_resource(
  'setup-s3-bucket',
  resource_deps=['minio'],
)
k8s_resource(
  'delete-all-files',
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  resource_deps=['setup-s3-bucket'],
)

k8s_yaml('jaeger.yaml')
k8s_resource('jaeger', port_forwards=['16686'])

k8s_yaml('prometheus.yaml')
k8s_resource('prometheus', port_forwards=['9090'])
